batch_size: 8
num_epochs: 20
lr: 0.0001
use_cuda: true
src_seq_len: 350
tgt_seq_len: 350
d_model: 512
h: 8
lang_src: "en"
lang_tgt: "it"
model_folder: "en_to_it"
model_basename: "model_at_epoch_"
preload: null
tokenizer_file: "tokenizer_{0}.json"
